# Generated by Django 4.1.5 on 2023-02-10 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('add_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('comment', models.TextField()),
                ('data_time', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=255, verbose_name='Association')),
                ('user_comment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='add_content.media_models', verbose_name='Model_ID')),
            ],
            options={
                'verbose_name': 'Comment',
                'ordering': ['-data_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.comments')),
            ],
            bases=('main.comments',),
        ),
    ]
