# Generated by Django 4.1.5 on 2023-02-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last_name')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('photo', models.ImageField(blank=True, upload_to='img/avatar', verbose_name='Foto_avatar')),
                ('data_time_create', models.DateTimeField(auto_now_add=True)),
                ('data_time_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User personal profile',
                'ordering': ['name'],
            },
        ),
    ]
